name: PR Target Validation

# This workflow validates PR target branches only (not branch names)
# Branch naming is enforced locally via git hooks (see LOCAL_ENFORCEMENT.md)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-target:
    name: Validate PR Target Branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR workflow (safety net)
        run: |
          echo "Note: Branch naming is enforced locally via git hooks"
          echo "This check validates PR target branch relationships only"
          echo ""

      - name: Check PR target branch
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"

          echo "PR: $SOURCE_BRANCH → $TARGET_BRANCH"

          # Validate PR targets
          if [[ "$TARGET_BRANCH" == "main" ]]; then
            # Only develop or hotfix/* can merge to main
            if [[ "$SOURCE_BRANCH" != "develop" ]] && [[ "$SOURCE_BRANCH" != hotfix/* ]]; then
              echo "❌ Only 'develop' or 'hotfix/*' branches can merge to 'main'"
              echo "Current: $SOURCE_BRANCH → main"
              echo ""
              echo "Workflow:"
              echo "  1. Merge feature branches to 'develop' first"
              echo "  2. Then merge 'develop' to 'main'"
              echo ""
              echo "For hotfixes:"
              echo "  hotfix/* → main (allowed)"
              exit 1
            fi
          elif [[ "$TARGET_BRANCH" == "develop" ]]; then
            # Feature branches merge to develop
            if [[ "$SOURCE_BRANCH" == "main" ]]; then
              echo "❌ Cannot merge 'main' to 'develop'"
              exit 1
            fi
          fi

          echo "✓ Valid PR target"
