name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"
      - "*/v*.*.*" # For crate-specific tags like "core/v1.0.0"
  workflow_dispatch:
    inputs:
      crate:
        description: 'Crate to release (or "all")'
        required: true
        type: string
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  # Determine what to build
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      crates: ${{ steps.detect.outputs.crates }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed crates
        id: detect
        run: |
          # If triggered by tag, extract crate name
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${{ github.ref_name }}"
            if [[ "$TAG" == */* ]]; then
              CRATE="${TAG%/*}"
              echo "crates=[\"$CRATE\"]" >> $GITHUB_OUTPUT
            else
              echo "crates=[\"all\"]" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ inputs.crate }}" == "all" ]]; then
              echo "crates=[\"all\"]" >> $GITHUB_OUTPUT
            else
              echo "crates=[\"${{ inputs.crate }}\"]" >> $GITHUB_OUTPUT
            fi
          fi

  # Build static binaries for all platforms
  build:
    name: Build - ${{ matrix.target }}
    needs: detect-changes
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64 (RHEL, CentOS, Fedora, Debian, Ubuntu compatible)
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false

          # Linux x86_64 musl (fully static)
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true

          # macOS Intel
          - target: x86_64-apple-darwin
            os: macos-13 # Intel runner
            cross: false

          # macOS ARM (Apple Silicon)
          - target: aarch64-apple-darwin
            os: macos-14 # ARM runner
            cross: false

          # Windows x86_64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Static linking configuration
      - name: Configure static linking (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV

      - name: Configure static linking (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $env:GITHUB_ENV

      - name: Build
        run: |
          if [[ "${{ matrix.cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }} --all-features
          else
            cargo build --release --target ${{ matrix.target }} --all-features
          fi
        shell: bash

      - name: Package artifacts
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/*.dll artifacts/ 2>/dev/null || true
            cp target/${{ matrix.target }}/release/*.lib artifacts/ 2>/dev/null || true
            7z a artifacts-${{ matrix.target }}.zip ./artifacts/*
          else
            cp target/${{ matrix.target }}/release/*.so artifacts/ 2>/dev/null || true
            cp target/${{ matrix.target }}/release/*.a artifacts/ 2>/dev/null || true
            cp target/${{ matrix.target }}/release/*.dylib artifacts/ 2>/dev/null || true
            tar -czf artifacts-${{ matrix.target }}.tar.gz -C artifacts .
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            artifacts-${{ matrix.target }}.tar.gz
            artifacts-${{ matrix.target }}.zip

  # Generate release notes
  generate-release-notes:
    name: Generate Release Notes
    needs: build
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.notes.outputs.notes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: notes
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          CURRENT_TAG="${{ github.ref_name }}"

          echo "# Release Notes - $CURRENT_TAG" > release_notes.md
          echo "" >> release_notes.md

          if [ -n "$PREV_TAG" ]; then
            echo "## Changes since $PREV_TAG" >> release_notes.md
            echo "" >> release_notes.md
            
            # Group commits by type
            echo "### ðŸŽ‰ Features" >> release_notes.md
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^feat" >> release_notes.md || true
            echo "" >> release_notes.md
            
            echo "### ðŸ› Bug Fixes" >> release_notes.md
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^fix" >> release_notes.md || true
            echo "" >> release_notes.md
            
            echo "### ðŸ“š Documentation" >> release_notes.md
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^docs" >> release_notes.md || true
            echo "" >> release_notes.md
            
            echo "### ðŸš€ Performance" >> release_notes.md
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^perf" >> release_notes.md || true
            echo "" >> release_notes.md
            
            echo "### â™»ï¸ Refactoring" >> release_notes.md
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^refactor" >> release_notes.md || true
            echo "" >> release_notes.md
          fi

          # Save notes
          cat release_notes.md
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md

  # Create GitHub Release
  create-release:
    name: Create GitHub Release
    needs: [build, generate-release-notes]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ needs.generate-release-notes.outputs.notes }}
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish to GitHub Packages (private registry)
  publish:
    name: Publish to GitHub Packages
    needs: [build, create-release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cargo for GitHub Packages
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << EOF
          [registries.github]
          index = "sparse+https://github.com/${{ github.repository_owner }}/_cargo-index/"

          [net]
          git-fetch-with-cli = true
          EOF

      - name: Login to GitHub Packages
        run: |
          cargo login --registry github ${{ secrets.GITHUB_TOKEN }}

      - name: Publish crates
        run: |
          # Publish in dependency order
          for crate in $(find . -name Cargo.toml -not -path "*/target/*" -not -path "*/_workspace-hack/*" | xargs dirname); do
            echo "Publishing $crate"
            cd $crate
            cargo publish --registry github --allow-dirty || echo "Skipping $crate (may already be published)"
            cd -
          done
