name: Smart CI - Affected Crates Only

# This workflow tests only crates affected by code changes (optimization)
# Git workflow enforcement (commits, branches, merges) happens locally via git hooks
# See LOCAL_ENFORCEMENT.md for details

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Detect which crates are affected by changes (smart testing)
  detect-affected:
    name: Detect Affected Crates
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.detect.outputs.affected }}
      all-affected: ${{ steps.detect.outputs.all-affected }}
      has-changes: ${{ steps.detect.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect affected crates
        id: detect
        run: |
          # Get changed files
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
          fi

          echo "Comparing $BASE_SHA...$HEAD_SHA"
          CHANGED_FILES=$(git diff --name-only $BASE_SHA...$HEAD_SHA || echo "")

          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected"
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "affected=[]" >> $GITHUB_OUTPUT
            echo "all-affected=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "has-changes=true" >> $GITHUB_OUTPUT
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Initialize affected crates list
          DIRECTLY_AFFECTED=()

          # Check for workspace-level changes
          WORKSPACE_CHANGED=false
          if echo "$CHANGED_FILES" | grep -qE '^(Cargo.toml|Cargo.lock|dependency-versions.toml|rust-toolchain.toml|\.cargo/)'; then
            WORKSPACE_CHANGED=true
            echo "Workspace-level files changed - will test all crates"
          fi

          # Find all crates
          ALL_CRATES=$(find . -name Cargo.toml -not -path "*/target/*" -not -path "*/_workspace-hack/*" | xargs dirname | sed 's|^\./||' | sort)

          if [ "$WORKSPACE_CHANGED" = true ]; then
            # Test all crates if workspace files changed
            for crate in $ALL_CRATES; do
              DIRECTLY_AFFECTED+=("$crate")
            done
          else
            # Check which crates have changes
            for crate in $ALL_CRATES; do
              if echo "$CHANGED_FILES" | grep -q "^$crate/"; then
                echo "Direct change detected in: $crate"
                DIRECTLY_AFFECTED+=("$crate")
              fi
            done
          fi

          # Build dependency graph and find all affected crates
          # (including crates that depend on changed crates)
          ALL_AFFECTED_CRATES=("${DIRECTLY_AFFECTED[@]}")

          # For each directly affected crate, find dependents
          for changed_crate in "${DIRECTLY_AFFECTED[@]}"; do
            for crate in $ALL_CRATES; do
              if [ "$crate" != "$changed_crate" ] && [ -f "$crate/Cargo.toml" ]; then
                # Check if this crate depends on the changed crate
                if grep -q "path.*=.*\"../$changed_crate\"" "$crate/Cargo.toml" 2>/dev/null; then
                  if [[ ! " ${ALL_AFFECTED_CRATES[@]} " =~ " ${crate} " ]]; then
                    echo "Transitive dependency detected: $crate depends on $changed_crate"
                    ALL_AFFECTED_CRATES+=("$crate")
                  fi
                fi
              fi
            done
          done

          # Convert to JSON arrays
          if [ ${#DIRECTLY_AFFECTED[@]} -eq 0 ]; then
            echo "affected=[]" >> $GITHUB_OUTPUT
            echo "all-affected=[]" >> $GITHUB_OUTPUT
          else
            AFFECTED_JSON=$(printf '%s\n' "${DIRECTLY_AFFECTED[@]}" | jq -R . | jq -s .)
            ALL_AFFECTED_JSON=$(printf '%s\n' "${ALL_AFFECTED_CRATES[@]}" | jq -R . | jq -s .)
            echo "affected=$AFFECTED_JSON" >> $GITHUB_OUTPUT
            echo "all-affected=$ALL_AFFECTED_JSON" >> $GITHUB_OUTPUT
            
            echo "Directly affected crates: ${DIRECTLY_AFFECTED[@]}"
            echo "All affected crates (including dependents): ${ALL_AFFECTED_CRATES[@]}"
          fi

  # Lint (always run)
  lint:
    name: Lint (Clippy & Format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # Test affected crates only
  test-affected:
    name: Test Affected - ${{ matrix.crate }} - Rust ${{ matrix.rust }}
    needs: detect-affected
    if: needs.detect-affected.outputs.has-changes == 'true' && needs.detect-affected.outputs.all-affected != '[]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, 1.81.0, 1.80.0]
        crate: ${{ fromJson(needs.detect-affected.outputs.all-affected) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ matrix.crate }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build ${{ matrix.crate }}
        run: cargo build --release -p ${{ matrix.crate }} --all-features

      - name: Test ${{ matrix.crate }}
        run: cargo test --release -p ${{ matrix.crate }} --all-features

  # Test nightly for affected crates
  test-nightly-affected:
    name: Test Affected (Nightly) - ${{ matrix.crate }}
    needs: detect-affected
    if: needs.detect-affected.outputs.has-changes == 'true' && needs.detect-affected.outputs.all-affected != '[]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crate: ${{ fromJson(needs.detect-affected.outputs.all-affected) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-nightly-${{ matrix.crate }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build ${{ matrix.crate }}
        run: cargo build --release -p ${{ matrix.crate }} --all-features

      - name: Test ${{ matrix.crate }}
        run: cargo test --release -p ${{ matrix.crate }} --all-features

  # If no changes detected
  no-changes:
    name: No Changes Detected
    needs: detect-affected
    if: needs.detect-affected.outputs.has-changes == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip tests
        run: |
          echo "No changes detected - skipping tests"
          echo "This is expected for certain events like workflow_dispatch with no code changes"

  # Summary job
  test-summary:
    name: Test Summary
    needs: [detect-affected, test-affected, test-nightly-affected]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test-affected.result }}" == "failure" ] || [ "${{ needs.test-nightly-affected.result }}" == "failure" ]; then
            echo "Some tests failed"
            exit 1
          elif [ "${{ needs.detect-affected.outputs.has-changes }}" == "false" ]; then
            echo "No changes detected - tests skipped"
            exit 0
          else
            echo "All tests passed!"
            exit 0
          fi
